# Generated by Django 4.1.5 on 2023-12-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="datecompleted",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
